version: '3.8'

services:
  db:
      container_name: postgres
      image: postgres:alpine
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: meteorium
      ports:
        - "127.0.0.1:5432:5432"
      volumes:
        - ./postgres_data:/var/lib/postgresql/data/
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d meteorium"]
        interval: 10s
        timeout: 5s
        retries: 5
  migrations:
      build: ./db-migrations
      container_name: meteorium-migrations
      depends_on:
        - db